# Generated by Django 3.0.8 on 2020-08-03 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pre_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='create_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeetingRoomBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('applyed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyer', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('meetin_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManager.MeetingRoom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManager.Order')),
            ],
        ),
    ]
