# Generated by Django 3.0.8 on 2020-08-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0002_auto_20200803_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extra_info',
        ),
    ]
